export default {
  id: "cline",
  priority: 80,
  alias: "cl",
  uiAlias: "cl",
  display: {
    name: "Cline",
    icon: "smart_toy",
    color: "#5B9BD5",
    textIcon: "CL",
    website: "https://cline.bot",
    notice: {
      signupUrl: "https://cline.bot",
    },
  },
  category: "oauth",
  authModes: ["oauth"],
  hasOAuth: true,
  transport: {
    baseUrl: "https://api.cline.bot/api/v1/chat/completions",
    headers: {
      "HTTP-Referer": "https://cline.bot",
      "X-Title": "Cline",
    },
    // Non-stream chat completions come back wrapped in {"success":true,"data":{...}}
    quirks: { clineEnvelope: true },
    tokenUrl: "https://api.cline.bot/api/v1/auth/token",
    refreshUrl: "https://api.cline.bot/api/v1/auth/refresh",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
      hooks: [
        "clineHeaders",
      ],
    },
  },
  models: [
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "openai/gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "openai/gpt-5.4", name: "GPT-5.4" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "kwaipilot/kat-coder-pro", name: "KAT Coder Pro" },
  
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", upstreamModelId: "anthropic/claude-opus-5" },
    { id: "claude-opus-5", name: "Claude Opus 5", upstreamModelId: "anthropic/claude-opus-5" },
    { id: "zai/glm-5.2", name: "GLM 5.2", upstreamModelId: "zai/glm-5.2" },
    { id: "glm-5.2", name: "GLM 5.2", upstreamModelId: "zai/glm-5.2" },
    { id: "x-ai/grok-4.5", name: "Grok 4.5", upstreamModelId: "x-ai/grok-4.5" },
    { id: "grok-4.5", name: "Grok 4.5", upstreamModelId: "x-ai/grok-4.5" },
    { id: "openai/gpt-5.6-sol", name: "GPT-5.6 Sol", upstreamModelId: "openai/gpt-5.6-sol" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", upstreamModelId: "openai/gpt-5.6-sol" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3", upstreamModelId: "moonshotai/kimi-k3" },
    { id: "kimi-k3", name: "Kimi K3", upstreamModelId: "moonshotai/kimi-k3" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash", upstreamModelId: "deepseek/deepseek-v4-flash" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", upstreamModelId: "deepseek/deepseek-v4-flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", upstreamModelId: "deepseek/deepseek-v4-pro" },
    { id: "poolside/laguna-s-2.1:free", name: "Laguna S 2.1 (Free)", upstreamModelId: "poolside/laguna-s-2.1:free" },
    { id: "laguna-s-2.1:free", name: "Laguna S 2.1 (Free)", upstreamModelId: "poolside/laguna-s-2.1:free" },
    { id: "stepfun/step-3.7-flash", name: "Step 3.7 Flash", upstreamModelId: "stepfun/step-3.7-flash" },
    { id: "step-3.7-flash", name: "Step 3.7 Flash", upstreamModelId: "stepfun/step-3.7-flash" },
    { id: "anthropic/claude-opus-4-7", name: "Claude Opus 4.7", upstreamModelId: "anthropic/claude-opus-4-7" },
    { id: "anthropic/claude-opus-4-6", name: "Claude Opus 4.6", upstreamModelId: "anthropic/claude-opus-4-6" },
    { id: "anthropic/claude-sonnet-4-6", name: "Claude Sonnet 4.6", upstreamModelId: "anthropic/claude-sonnet-4-6" },
    { id: "anthropic/claude-3-7-sonnet", name: "Claude 3.7 Sonnet", upstreamModelId: "anthropic/claude-3-7-sonnet" },
    { id: "openai/gpt-4o", name: "GPT-4o", upstreamModelId: "openai/gpt-4o" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro", upstreamModelId: "google/gemini-2.5-pro" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek Chat", upstreamModelId: "deepseek/deepseek-chat" },
    { id: "minimax/minimax-m2.5", name: "MiniMax M2.5 (Free)", upstreamModelId: "minimax/minimax-m2.5" },
    { id: "stealth/ox-alpha", name: "0x-Alpha", upstreamModelId: "stealth/ox-alpha" },
  ],
  oauth: {
    appBaseUrl: "https://app.cline.bot",
    apiBaseUrl: "https://api.cline.bot",
    authorizeUrl: "https://api.cline.bot/api/v1/auth/authorize",
    tokenExchangeUrl: "https://api.cline.bot/api/v1/auth/token",
    refreshUrl: "https://api.cline.bot/api/v1/auth/refresh",
  },
};
