// xKiro — AI model gateway (api.xkiro.com), first-class API-key provider.
//
// OpenAI-compatible /v1/chat/completions (streaming, tools, vision, reasoning)
// plus an Anthropic-compatible /v1/messages dialect on the same host — both
// dialects accept the same reasoning intent (reasoning_effort OR thinking
// blocks), so the OpenAI chat dialect alone covers every client format.
//
// Auth: Bearer sk-xt-… (or x-api-key — equivalent). Model ids are ALWAYS
// vendor-prefixed (openai/gpt-5.6-sol); a bare name 404s. Blocking requests
// are cut off at 95s upstream — reasoning models on large prompts must stream.
//
// Catalog + capabilities + pricing below are generated from the LIVE
// /v1/models response (public, 2026-09-06 snapshot, 112 chat models): each
// model carries pricing (per-1M USD), capabilities (vision/reasoning),
// context_length, max_output_tokens and reasoning_efforts {levels, default}.
// Per xKiro docs, models WITHOUT a reasoning_efforts object ignore reasoning
// parameters entirely — those are registered with reasoning:false so the
// thinking picker is hidden instead of advertising controls that do nothing.
//
// No custom executor needed — DefaultExecutor handles the OpenAI-compatible
// API (Bearer auth, streaming, image_url vision passthrough; images sent to
// non-vision models are replaced with a note upstream instead of failing).
export default {
  id: "xkiro",
  priority: 322,
  alias: "xkiro",
  aliases: [],
  uiAlias: "xk",
  display: {
    name: "xKiro",
    icon: "key",
    color: "#6366F1",
    textIcon: "XK",
    website: "https://xkiro.com",
    notice: {
      signupUrl: "https://xkiro.com",
      apiKeyUrl: "https://xkiro.com",
      text: "xKiro is an AI gateway hosting 100+ models (GPT, Claude, Gemini, GLM, Kimi, DeepSeek, Qwen, MiniMax, Mistral) behind one sk-xt- API key. Reasoning intent is translated per model; models without reasoning control ignore it at no cost. GET /v1/usage reports spend windows and wallet with the same key.",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  // BOTH flags required: `usage` gates USAGE_SUPPORTED_PROVIDERS (Quota UI
  // list), `usageApikey` gates USAGE_APIKEY_PROVIDERS (api-key connections
  // allowed past the authType check). /v1/usage is free to call with the
  // chat key — no separate management key (unlike TokenRouter).
  features: { usage: true, usageApikey: true },
  transport: {
    baseUrl: "https://api.xkiro.com/v1/chat/completions",
    format: "openai",
    thinkingFormat: "openai",
    validateUrl: "https://api.xkiro.com/v1/models",
    usage: { url: "https://api.xkiro.com/v1/usage" },
  },
  thinkingConfig: {
    options: ["auto", "none", "minimal", "low", "medium", "high", "xhigh", "max"],
    defaultMode: "auto",
  },
  models: [
    { id: "anthropic/claude-fable-5", name: "Fable 5" },
    { id: "anthropic/claude-fable-5-1", name: "Fable 5.1" },
    { id: "anthropic/claude-haiku-4.5", name: "Haiku 4.5" },
    { id: "anthropic/claude-opus-4.6", name: "Opus 4.6" },
    { id: "anthropic/claude-opus-4.7", name: "Opus 4.7" },
    { id: "anthropic/claude-opus-4.8", name: "Opus 4.8" },
    { id: "anthropic/claude-opus-5", name: "Opus 5" },
    { id: "anthropic/claude-sonnet-4.6", name: "Sonnet 4.6" },
    { id: "anthropic/claude-sonnet-5", name: "Sonnet 5" },
    { id: "deepseek/deepseek-chat-v3.1", name: "DeepSeek V3.1" },
    { id: "deepseek/deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek/deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731" },
    { id: "deepseek/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 0813" },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "google/gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "google/gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash" },
    { id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2" },
    { id: "minimax/minimax-m2:free", name: "MiniMax M2 (Free)" },
    { id: "minimax/minimax-m2.1-highspeed:free", name: "MiniMax M2.1 Highspeed (Free)" },
    { id: "minimax/minimax-m2.1:free", name: "MiniMax M2.1 (Free)" },
    { id: "minimax/minimax-m2.5", name: "MiniMax M2.5" },
    { id: "minimax/minimax-m2.5-highspeed:free", name: "MiniMax M2.5 Highspeed (Free)" },
    { id: "minimax/minimax-m2.5:free", name: "MiniMax M2.5 (Free)" },
    { id: "minimax/minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax/minimax-m2.7-highspeed:free", name: "MiniMax M2.7 Highspeed (Free)" },
    { id: "minimax/minimax-m2.7:free", name: "MiniMax M2.7 (Free)" },
    { id: "minimax/minimax-m3", name: "MiniMax M3" },
    { id: "minimax/minimax-m3:free", name: "MiniMax M3 (Free)" },
    { id: "mistralai/codestral-2508", name: "Codestral" },
    { id: "mistralai/devstral-medium", name: "Devstral 2" },
    { id: "mistralai/ministral-14b", name: "Ministral 3 14B" },
    { id: "mistralai/ministral-3b", name: "Ministral 3 3B" },
    { id: "mistralai/ministral-8b", name: "Ministral 3 8B" },
    { id: "mistralai/mistral-large-2512", name: "Mistral Large 3" },
    { id: "mistralai/mistral-medium-3.5", name: "Mistral Medium 3.5" },
    { id: "mistralai/mistral-small-2603", name: "Mistral Small 4" },
    { id: "moonshotai/kimi-k2.5", name: "Kimi K2.5" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "nvidia/llama-3.3-nemotron-super-49b", name: "Llama 3.3 Nemotron Super 49B" },
    { id: "nvidia/nemotron-3-nano", name: "Nemotron 3 Nano" },
    { id: "nvidia/nemotron-3-nano-omni", name: "Nemotron 3 Nano Omni" },
    { id: "nvidia/nemotron-3-super", name: "Nemotron 3 Super" },
    { id: "nvidia/nemotron-3-ultra", name: "Nemotron 3 Ultra" },
    { id: "openai/gpt-5.3-codex-spark", name: "Codex 5.3 Spark" },
    { id: "openai/gpt-5.4", name: "GPT-5.4" },
    { id: "openai/gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "openai/gpt-5.5", name: "GPT-5.5" },
    { id: "openai/gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "openai/gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "openai/gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "openai/gpt-6-astra", name: "GPT-6 Astra" },
    { id: "qwen/qwen-plus-2025-07-28:free", name: "Qwen Plus 0728 (Free)" },
    { id: "qwen/qwen3-coder-plus:free", name: "Qwen3 Coder Plus (Free)" },
    { id: "qwen/qwen3-max:free", name: "Qwen3 Max (Free)" },
    { id: "qwen/qwen3-omni-flash:free", name: "Qwen3 Omni Flash (Free)" },
    { id: "qwen/qwen3-vl-plus:free", name: "Qwen3 VL Plus (Free)" },
    { id: "qwen/qwen3.5-397b-a17b:free", name: "Qwen3.5 397B A17B (Free)" },
    { id: "qwen/qwen3.5-flash:free", name: "Qwen3.5 Flash (Free)" },
    { id: "qwen/qwen3.5-omni-flash:free", name: "Qwen3.5 Omni Flash (Free)" },
    { id: "qwen/qwen3.5-omni-plus:free", name: "Qwen3.5 Omni Plus (Free)" },
    { id: "qwen/qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "qwen/qwen3.5-plus:free", name: "Qwen3.5 Plus (Free)" },
    { id: "qwen/qwen3.6-27b:free", name: "Qwen3.6 27B (Free)" },
    { id: "qwen/qwen3.6-35b-a3b:free", name: "Qwen3.6 35B A3B (Free)" },
    { id: "qwen/qwen3.6-max-preview:free", name: "Qwen3.6 Max Preview (Free)" },
    { id: "qwen/qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen/qwen3.6-plus:free", name: "Qwen3.6 Plus (Free)" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen/qwen3.7-max:free", name: "Qwen3.7 Max (Free)" },
    { id: "qwen/qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "qwen/qwen3.7-plus:free", name: "Qwen3.7 Plus (Free)" },
    { id: "qwen/qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen/qwen3.8-max:free", name: "Qwen3.8 Max (Free)" },
    { id: "sensenova/sensenova-6.7-flash-lite", name: "SenseNova 6.7 Flash-Lite" },
    { id: "sensenova/sensenova-6.8-flash-lite", name: "SenseNova 6.8 Flash-Lite" },
    { id: "tencent/hy3", name: "Hy3" },
    { id: "tencent/hy4-preview", name: "Hy4 Preview" },
    { id: "x-ai/grok-4.5", name: "Grok 4.5" },
    { id: "x-ai/grok-4.6", name: "Grok 4.6" },
    { id: "x-ai/grok-build-0.1", name: "Grok Build 0.1" },
    { id: "xiaomi/mimo-v2.5", name: "MiMo v2.5" },
    { id: "xiaomi/mimo-v2.5-pro", name: "MiMo v2.5 Pro" },
    { id: "z-ai/glm-4.5", name: "GLM-4.5" },
    { id: "z-ai/glm-4.5-air", name: "GLM-4.5 Air" },
    { id: "z-ai/glm-4.5-airx", name: "GLM-4.5 AirX" },
    { id: "z-ai/glm-4.5-flash", name: "GLM-4.5 Flash" },
    { id: "z-ai/glm-4.5-x", name: "GLM-4.5-X" },
    { id: "z-ai/glm-4.5v", name: "GLM-4.5V" },
    { id: "z-ai/glm-4.6", name: "GLM-4.6" },
    { id: "z-ai/glm-4.6v", name: "GLM-4.6V" },
    { id: "z-ai/glm-4.6v-flash", name: "GLM-4.6V Flash" },
    { id: "z-ai/glm-4.6v-flashx", name: "GLM-4.6V FlashX" },
    { id: "z-ai/glm-4.7", name: "GLM-4.7" },
    { id: "z-ai/glm-4.7-flash", name: "GLM-4.7 Flash" },
    { id: "z-ai/glm-4.7-flashx", name: "GLM-4.7 FlashX" },
    { id: "z-ai/glm-5", name: "GLM-5" },
    { id: "z-ai/glm-5-turbo", name: "GLM-5 Turbo" },
    { id: "z-ai/glm-5.1", name: "GLM-5.1" },
    { id: "z-ai/glm-5.2", name: "GLM-5.2" },
    { id: "z-ai/glm-5.3", name: "GLM-5.3" },
    { id: "z-ai/glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "z-ai/glm-5v-turbo", name: "GLM-5V Turbo" },
  ],
};
